name: Publish to Docker Hub

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Action to log in to Docker Hub
        with:
          username: ${{ secrets.NXERADOCKERHUBUSERNAME }}
          password: ${{ secrets.NXERADOCKERHUBSECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Action to build and push Docker images
        with:
          context: . # Directory containing your Dockerfile
          push: true # Push the image to Docker Hub
          tags: ${{ secrets.NXERADOCKERHUBUSERNAME }}/nx-health-checker:latest # Tag your image